"""Create item table

Revision ID: 36849fd78f92
Revises: 
Create Date: 2024-08-21 14:54:19.939982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36849fd78f92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    # ### end Alembic commands ###
